app/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from app import db


class User(db.Model):
    __table__ = db.Model.metadata.tables['user']


class City(db.Model):
    __table__ = db.Model.metadata.tables['city']


class Forecast(db.Model):
    __table__ = db.Model.metadata.tables['forecast']

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, StringField, PasswordField
from werkzeug.routing import ValidationError
from wtforms.validators import DataRequired, Email, Length

from app.models import User


class searchForm(FlaskForm):
   city = StringField('City', validators=[DataRequired(), Length(min=2, max=20)])
   submit = SubmitField('Search')

class signupForm(FlaskForm):
   username = StringField('Username', validators=[DataRequired(), Length(min=5, max=16)])
   email = StringField('Email address', validators=[DataRequired(), Email()])
   password = PasswordField('Password', validators=[DataRequired(), Length(min=8, max=16)])
   submit = SubmitField('Sign Up')

   def validateEmail(self, email):
      user = User.query.filter_by(email=email.data).first()
      if user is not None:
         raise ValidationError('An account already exists for this email address.')

app/__init__.py
from flask import Flask, render_template, flash, redirect, url_for
from os.path import dirname, abspath, join
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

from config import DevConfig

def create_app(config_class=DevConfig):
    """
    Creates an application instance to run using settings from config.py
    :return: A Flask object
    """
    app = Flask(__name__)
    app.config.from_object(config_class)
    app.config['SECRET_KEY'] = "dfdQbTOExternjy5xmCNaA"
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    CWD = dirname(abspath(__file__))
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + join(CWD, 'rain.sqlite')

    # Initialise the database and create tables
    db.init_app(app)

    # The following is needed if you want to map classes to an existing database
    with app.app_context():
        db.Model.metadata.reflect(db.engine)

        # Register Blueprints
    from app.main.routes import bp_main
    app.register_blueprint(bp_main)

    return app

app/main/routes.py
from flask import render_template, Blueprint, url_for, request, flash, redirect
from app.main.forms import signupForm, searchForm
from app import db
from sqlalchemy.exc import IntegrityError
from app.models import User, City, Forecast


bp_main = Blueprint('main', __name__)

@bp_main.route('/', methods=['GET', 'POST'])
@bp_main.route('/home', methods=['GET', 'POST'])
def index():
    form = searchForm()
    cities = City.query.all()
    forecasts = Forecast.query.all()
    print(cities)
    if form.validate_on_submit():
        for city in cities:
            if form.city.data == city.city:
                cityID=city.city_id
                for forecast in forecasts:
                    if forecast.city_id == cityID:
                        flash(f'The forecast for {city.city} is {forecast.forecast}. Written on the {forecast.forecast_datetime}')

        return redirect(url_for('index'))
    return render_template('index.html', cities=cities, forecasts=forecasts, form=form)


@bp_main.route('/signup', methods=['GET', 'POST'])
def signup():
    form = signupForm()
    if request.method == 'POST' and form.validate():
        user = User(username=form.username.data, email=form.email.data)
        try:
            db.session.add(user)
            db.session.commit()
            flash('You have registered as a user.')
        except IntegrityError:
            db.session.rollback()
            flash('Cannot register {}.'.format(form.email.data), 'error')
        return redirect(url_for('main.index'))
    return render_template('signup.html', form=form)

@bp_main.route('/user', methods=['GET'])
def users():
    user_list = User.query.all()
    return render_template("user.html", users=user_list)

@bp_main.route('/search', methods=['POST', 'GET'])
def search():
    if request.method == 'POST':
        term = request.form['search_term']
        if term == "":
            flash("Enter a city to search for")
            return redirect('/')
        results = City.query.filter(City.city.contains(term)).all()
        results = City.query.join(Forecast).with_entities(City.city, Forecast.forecast_datetime,Forecast.forecast, Forecast.comment).filter(City.city.contains(term)).all()
        if not results:
            flash("No city found with that name.")
            return redirect('/')
        return render_template('search.html', results=results)
    else:
        return redirect(url_for('main.index'))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {#  Allows each page title to be set using a variable named 'title' #}
        {% block title %}{{ title }}{% endblock %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <nav class="navbar navbar-dark bg-primary">
                <span class="navbar-text mb-0 h2">
                    Rain Forecast Blog
                </span>
                <div class="col-md-6">
                    <a class="btn btn-secondary" href="{{ url_for("main.index") }}"
                      role="button">Home
                    </a>
                    <a class="btn btn-secondary" href="{{ url_for("main.signup") }}"
                      role="button">Sign Up
                    </a>
                    <a class="btn btn-secondary" href="{{ url_for("main.users") }}"
                      role="button">User List
                    </a>
                </div>
            </nav>
        </div>
    </div>
</div>
<div role=main class="container-fluid">
    {# Displays flashed messages on a page #}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}

    {# Child pages add page specific content here #}
    {% block content %}
    {% endblock %}

</div>
</body>
</html>

app/templates/index.html
<!-- Use the base template -->
{% extends "base.html" %}

<!-- Title for this page -->
{% block title %}Rain Forecast Blog Page {% endblock %}

<!-- Content for this page -->
{% block content %}
    <div class="container-fluid">
    <br>
        <div class="row">
            <div class="col-md-8">
                <h1>
                    RAIN FORECASTS
                </h1>
                <p>
                    Dolor magna eget est lorem ipsum dolor. Phasellus egestas tellus rutrum tellus pellentesque. Ultrices tincidunt arcu non sodales neque sodales. Iaculis urna id volutpat lacus laoreet non curabitur. Adipiscing commodo elit at imperdiet dui accumsan sit. Gravida rutrum quisque non tellus orci. Ultrices neque ornare aenean euismod elementum nisi quis eleifend. Odio facilisis mauris sit amet massa vitae tortor condimentum lacinia. Diam vulputate ut pharetra sit amet aliquam id diam maecenas. Amet cursus sit amet dictum. Nunc mattis enim ut tellus elementum sagittis. A condimentum vitae sapien pellentesque habitant morbi tristique senectus. Pretium vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae. In iaculis nunc sed augue lacus viverra vitae congue.
                </p>
            </div>
            <div class="col-md-4">
                <form class="form-inline">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
            <div class="col-md-12">
                <p>
                    ajwdnwakjdnwakjndkwajdnakjwdnkawdnkajw
                </p>
            </div>
        </div>
</div>
{% endblock %}

app/templates/search.html
{% extends "base.html" %}
{% block title %}Search Results:{% endblock %}
{% block content %}
    {% if results|length %}
    {# Variable is not empty #}
        <table class="table">
            <thead class="thead-light">
            <tr>
                <th scope="col">City name</th>
                <th scope="col">Date</th>
                <th scope="col">Forecast</th>
                <th scope="col">Comment</th>
            </tr>
            </thead>
            <tbody>
            {% for result in results %}
                <tr>
                    <td>{{ result.city }}</td>
                    <td>{{ result.forecast_datetime }}</td>
                    <td>{{ result.forecast }}</td>
                    <td>{{ result.comment }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
    {# Variable is empty #}
        <p>No cities found.</p>
    {% endif %}
{% endblock %}

app/templates/signup.html
{% extends "base.html" %}
{% block title %}Rain Forecast Blog{% endblock %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                {% if form.errors %}
                    <p><strong>Incorrect entry, please re-enter.</strong>
                    <ul>
                        {% for error in form.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
                <form action="" method="post" novalidate>
                    {{ form.hidden_tag() }}
                    <p>{{ form.username.label }}<br>{{ form.username(size=32) }}</p>
                    <p>{{ form.email.label }}<br>{{ form.email(size=32) }}</p>
                    <p>{{ form.password.label }}<br>{{ form.password }}</p>
                    <p>{{ form.submit() }}</p>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/user.html
{% extends "base.html" %}
{% block title %}Registered users{% endblock %}
{% block content %}
    {% if users|length %}
        <table class="table">
            <thead class="thead-light">
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
            </tr>
            </thead>
            <tbody>
            {% for user in users %}
            <tr>
                <td>{{ user.username }}</td>
                <td>{{ user.email }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>Currently empty.</p>
    {% endif %}
{% endblock %}